[project]
name = "slangpy-imgui-bundle"
version = "0.1.0"
description = "A slangpy renderer for ImGui Bundle."
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
